version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:14.21
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  CSS_MODE: ${CSS_MODE-optimized}
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}
  NODE_ENV: development
  SENDGRID_API_KEY: ${SENDGRID_API_KEY-(unset)}
  SENDGRID_DEV_TO: ${SENDGRID_DEV_TO-support@parameter1.com}
  YARN_CACHE_FOLDER: /.yarn-cache
  IDENTITYX_API_TOKEN: ${IDENTITYX_API_TOKEN-(unset)}
  IDENTITYX_GRAPHQL_URI: ${IDENTITYX_GRAPHQL_URI-https://identity-x.parameter1.com/graphql}
  BASE_BROWSE_GRAPHQL_URI: ${BASE_BROWSE_GRAPHQL_URI-https://base-browse.leonis.base.parameter1.com/graphql}
  ENABLE_CONTENT_METER: ${ENABLE_CONTENT_METER-false}
  IDX_NAV_ENABLE: ${IDX_NAV_ENABLE-false}
  RECAPTCHA_V3_SITE_KEY: ${RECAPTCHA_V3_SITE_KEY-(unset)}
  RECAPTCHA_V3_SECRET_KEY: ${RECAPTCHA_V3_SECRET_KEY-(unset)}
  OMEDA_APP_ID: ${OMEDA_APP_ID-}
  OMEDA_INPUT_ID: ${OMEDA_INPUT_ID-}

x-env-leonis: &env-leonis
  GRAPHQL_URI: ${GRAPHQL_URI-https://graphql.leonis.base.parameter1.com}
  OEMBED_URI: ${OEMBED_URI-https://oembed.leonis.base.parameter1.com}
  RSS_URI: ${RSS_URI-https://rss.leonis.base.parameter1.com}
  SITEMAPS_URI: ${SITEMAPS_URI-https://sitemaps.leonis.base.parameter1.com}

x-site-command: &site-cmd
  <<: *node
  entrypoint: ["yarn"]
  command: ["dev"]

volumes:
  yarn-cache: {}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  feedandgrain:
    <<: *site-cmd
    working_dir: /root/sites/feedandgrain.com
    environment:
      <<: *env
      HOST: www-feedandgrain.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9925
      LIVERELOAD_PORT: 19925
    hostname: www-feedandgrain.dev.parameter1.com
    ports:
      - "9925:80"
      - "19925:19925"

  wattagnet:
    <<: *site-cmd
    working_dir: /root/sites/wattagnet.com
    environment:
      <<: *env
      HOST: www-wattagnet.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9926
      LIVERELOAD_PORT: 19926
    hostname: www-wattagnet.dev.parameter1.com
    ports:
      - "9926:80"
      - "19926:19926"

  feedstrategy:
    <<: *site-cmd
    working_dir: /root/sites/feedstrategy.com
    environment:
      <<: *env
      HOST: www-feedstrategy.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9927
      LIVERELOAD_PORT: 19927
    hostname: www-feedstrategy.dev.parameter1.com
    ports:
      - "9927:80"
      - "19927:19927"

  petfoodindustry:
    <<: *site-cmd
    working_dir: /root/sites/petfoodindustry.com
    environment:
      <<: *env
      HOST: www-petfoodindustry.dev.parameter1.com
      PORT: 80
      EXPOSED_PORT: 9928
      LIVERELOAD_PORT: 19928
    hostname: www-petfoodindustry.dev.parameter1.com
    ports:
      - "9928:80"
      - "19928:19928"
