name: Deploy sites (staging)

on:
  push:
    tags:
      - '*'

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    outputs:
      version: ${{ steps.tag_version.outputs.VERSION }}
      environment: staging

  pre-deploy:
    needs: [vars]
    runs-on: ubuntu-latest
    steps:
      - name: Notify start
        run: npx @parameter1/base-cms-website-deployment-tool notify-started
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: ${{ needs.vars.outputs.environment }}
          RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          TRAVIS_TAG: ${{ needs.vars.outputs.version }}

  deploy:
    needs: [vars, pre-deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace:
          - staging-websites-leonis
        site:
          - example.com
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Kubernetes
        run: npx @parameter1/base-cms-website-deployment-tool deploy ${{ matrix.site }} ${{ matrix.namespace }}
        env:
          DOCKER_ORG: ${{ secrets.DOCKER_ORG }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          ENVIRONMENT: ${{ needs.vars.outputs.environment }}
          RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
          TRAVIS_TAG: ${{ needs.vars.outputs.version }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          FORCE_DEPLOYMENT: 1

  post-deploy-failure:
    if: failure()
    needs: [vars, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify failure
        run: npx @parameter1/base-cms-website-deployment-tool notify-failed
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: ${{ needs.vars.outputs.environment }}
          RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          TRAVIS_TAG: ${{ needs.vars.outputs.version }}

  post-deploy-success:
    if: success()
    needs: [vars, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Notify success
        run: npx @parameter1/base-cms-website-deployment-tool notify-finished
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ENVIRONMENT: ${{ needs.vars.outputs.environment }}
          RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
          TRAVIS_REPO_SLUG: ${{ github.repository }}
          TRAVIS_TAG: ${{ needs.vars.outputs.version }}

  ######################
  # Add websites here! #
  ######################

  build-sites:
    needs: [vars]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
          - feedandgrain.com
          - wattagnet.com
          - petfoodindustry.com
          - feedstrategy.com

    steps:
      - uses: actions/checkout@v2
      - name: Log in to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.ECR_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            SITE=${{ matrix.site }}
          tags: ${{ env.ECR_REGISTRY }}/${{ env.IMG_PREFIX }}-${{ matrix.site }}:${{ needs.vars.outputs.version }}

  deploy-sites:
    needs: [vars, build-sites]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace:
          - staging-websites-leonis
        site:
          - feedandgrain.com
          - wattagnet.com
          - petfoodindustry.com
          - feedstrategy.com

    steps:
      - name: Deploy to Kubernetes
        run: |
          npx @parameter1/rancher2cli dl \
            --wait --namespace ${{ matrix.namespace }} \
            basecms-website ${{ env.IMG_PREFIX }}-${{ matrix.site }} \
            ${{ env.ECR_REGISTRY }}/${{ env.IMG_PREFIX }}-${{ matrix.site }}:${{ needs.vars.outputs.version }}
        env:
          RANCHER_CLUSTERID: c-7p6pt
          RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
          RANCHER_URL: ${{ secrets.RANCHER_URL }}
