name: Deploy sites (staging)

on:
  push:
    branches: [staging]

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: |
        REF=$(echo $GITHUB_REF | cut -d / -f 3)
        [[ "$GITHUB_REF" =~ ^refs/tags.*$ ]] && VERSION="$REF" || VERSION="${REF}-${GITHUB_SHA::7}"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.tag_version.outputs.version }}

  notify-start:
    needs: [version]
    uses: parameter1/actions/.github/workflows/notify-start.yml@main
    secrets: inherit
    with:
      version: ${{ needs.version.outputs.version }}

  post-deploy-failure:
    if: failure()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-fail.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  post-deploy-complete:
    if: success()
    needs: [notify-start, deploy-sites]
    uses: parameter1/actions/.github/workflows/notify-complete.yml@main
    secrets: inherit
    with:
      slack-thread: ${{ needs.notify-start.outputs.slack-thread }}

  ######################
  # Add websites here! #
  ######################

  build-sites:
    needs: [version]
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: feedandgrain.com, stack: leonis, id: 63daaa66da016482232f9f73, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedandgrain.com }
          - { dir: feedstrategy.com, stack: leonis, id: 63daaa97da016482232fe746, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedstrategy.com }
          - { dir: petfoodindustry.com, stack: leonis, id: 63daa5dfda01648223282de1, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-petfoodindustry.com }
          - { dir: wattagnet.com, stack: leonis, id: 63daa5abda0164822327dec2, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-wattagnet.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      docker_image: ${{ vars.AWS_ECR_REGISTRY }}/base-cms-websites-staging:${{ matrix.site.account }}-${{ matrix.site.dir }}-${{ needs.version.outputs.version }}
      site_id: ${{ matrix.site.id }}
      site_host: ${{ matrix.site.dir }}
      infra_stack: ${{ matrix.site.stack }}
      tenant_key: ${{ matrix.site.tenant }}
      push: true
    secrets: inherit

  deploy-sites:
    needs: [version, build-sites]
    uses: parameter1/actions/.github/workflows/website-deploy-staging.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: feedandgrain.com, stack: leonis, id: 63daaa66da016482232f9f73, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedandgrain.com }
          - { dir: feedstrategy.com, stack: leonis, id: 63daaa97da016482232fe746, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedstrategy.com }
          - { dir: petfoodindustry.com, stack: leonis, id: 63daa5dfda01648223282de1, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-petfoodindustry.com }
          - { dir: wattagnet.com, stack: leonis, id: 63daa5abda0164822327dec2, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-wattagnet.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: ${{ vars.AWS_ECR_REGISTRY }}/base-cms-websites-staging:${{ matrix.site.account }}-${{ matrix.site.dir }}-${{ needs.version.outputs.version }}
      infra_stack: ${{ matrix.site.stack }}
      rancher_label_key: basecms-website
      rancher_label_val: ${{ matrix.site.rancher_label }}
    secrets: inherit
