name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { id: 63daaa66da016482232f9f73, dir: feedandgrain.com, stack: leonis, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedandgrain.com }
          - { id: 63daaa97da016482232fe746, dir: feedstrategy.com, stack: leonis, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-feedstrategy.com }
          - { id: 63daa5dfda01648223282de1, dir: petfoodindustry.com, stack: leonis, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-petfoodindustry.com }
          - { id: 63daa5abda0164822327dec2, dir: wattagnet.com, stack: leonis, account: wattglobalmedia, tenant: wattglobalmedia_all, rancher_label: watt-global-media-wattagnet.com }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
      site_account: ${{ matrix.site.account }}
      site_dir: ${{ matrix.site.dir }}
      site_version: test
